name: Run Gitea and Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update and Clean System
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        sudo apt-get autoremove -y
        sudo rm -rf /var/lib/docker /var/lib/containerd

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        docker --version
        docker compose version

    - name: Create docker-compose.yml
      run: |
        echo 'version: "3.8"
        services:
          gitea:
            image: gitea/gitea:latest
            container_name: gitea
            ports:
              - "3000:3000"
              - "2222:22"
            volumes:
              - gitea_data:/data
            environment:
              - USER_UID=1000
              - USER_GID=1000
            depends_on:
              - db

          db:
            image: mariadb:latest
            container_name: gitea_db
            environment:
              - MYSQL_ROOT_PASSWORD=rootpassword
              - MYSQL_DATABASE=gitea
              - MYSQL_USER=gitea
              - MYSQL_PASSWORD=giteapassword
            volumes:
              - db_data:/var/lib/mysql

          py-runner:
            image: python:3.9-slim
            container_name: py_runner
            volumes:
              - ./A/Ven.py:/app/Ven.py
              - ./A/venompapa:/app/venompapa
            working_dir: /app
            command: >
              /bin/sh -c "
              chmod +x venompapa
              python3 Ven.py"
            depends_on:
              - gitea

        volumes:
          gitea_data:
          db_data:' > docker-compose.yml

    - name: Start Docker Services
      run: docker compose up -d

    - name: Check Running Containers
      run: docker ps

    - name: Verify Python Script Execution Logs
      run: docker logs py_runner
