name: Run Gitea and Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone Repository with Required Files
      run: |
        https://github.com/Ko0uu8/A.git
        

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Create docker-compose.yml
      run: |
        echo 'version: "3.8"
        services:
          gitea:
            image: gitea/gitea:latest
            container_name: gitea
            ports:
              - "3000:3000"
              - "2222:22"
            volumes:
              - gitea_data:/data
            environment:
              - USER_UID=1000
              - USER_GID=1000
            depends_on:
              - db

          db:
            image: mariadb:latest
            container_name: gitea_db
            environment:
              - MYSQL_ROOT_PASSWORD=rootpassword
              - MYSQL_DATABASE=gitea
              - MYSQL_USER=gitea
              - MYSQL_PASSWORD=giteapassword
            volumes:
              - db_data:/var/lib/mysql

          py-runner:
            image: python:3.9-slim
            container_name: py_runner
            volumes:
              
            command: >
              /bin/sh -c "
              chmod +x venompapa
              python3 Ven.py"
            depends_on:
              - gitea

        volumes:
          gitea_data:
          db_data:' > docker-compose.yml

    - name: Start Docker Services
      run: docker-compose up -d

    - name: Check Running Containers
      run: docker ps

    - name: Verify Python Script Execution Logs
      run: docker logs py_runner
